apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: manage-nodes
subjects:
- kind: ServiceAccount
  name: node-manager
  namespace: node-labels
roleRef:
  kind: ClusterRole
  name: manage-nodes
  apiGroup: rbac.authorization.k8s.io
